### ISSUE TITLE
Add "retry" to some base CI image

### ISSUE THREAD

**Issue by phil-davis** [owncloud-ci/retry#7]
https://github.com/owncloud/ocis/pull/4223 fetched "retry" into the nodejs image that is used in ocis CI.

Maybe we should add this "retry" script into some "base" CI image so that it is "just there" for the JS, PHP etc images in CI.

@xoxys do you know if it is already somewhere in the chain of docker images?

Where is best to put it?

**Comment by xoxys** [comment]
It is already in the node image but I mentioned it already in the initial discussion. Fetching it in ci is definetly the wrong way https://github.com/owncloud-ci/nodejs/blob/master/v16/Dockerfile.amd64#L15

Just add it in the same fashion to other reqired images so renovate will take care of updates.

**Comment by phil-davis** [comment]
Unneeded `curl` removed in https://github.com/owncloud/ocis/pull/4247

**Comment by phil-davis** [comment]
I guess that we might have a use for `retry` in the:
- `owncloudci/php` docker images. They do `composer` things fetch dependencies and might fail if upstream is rate-limiting, or behaving sub-optimally or...
- `owncloudci/golang` - that is used in CI where `make ci-go-generate` `make -C ocis build` etc happens. Those sort of commands have the potential to fail due to network, upstream server... issue

@xoxys please review https://github.com/owncloud-ci/golang/pull/91 and let me know if that looks correct.

**Comment by phil-davis** [comment]
https://github.com/owncloud-ci/golang/pull/91

https://github.com/owncloud-ci/php/pull/153

now `retry` is available with the images of all 3 languages commonly used in CI - go, js, php. That should be enough - we will mostly use `retry` for getting building, checking dependencies etc, with "package manager" type of tools of those languages.
